### ISSUE TITLE
Not found error

### ISSUE THREAD

**Issue by rasvaan** [rasvaan/digibird_api#31]
Upon first load an error is shown:

```
error:  Error: Not found
    at /Users/rasvaan/git/digibird_api/src/index.js:29:15
    at Layer.handle [as handle_request] (/Users/rasvaan/git/digibird_api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/rasvaan/git/digibird_api/node_modules/express/lib/router/index.js:312:13)
    at /Users/rasvaan/git/digibird_api/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/rasvaan/git/digibird_api/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/rasvaan/git/digibird_api/node_modules/express/lib/router/index.js:271:10)
    at cookieParser (/Users/rasvaan/git/digibird_api/node_modules/cookie-parser/index.js:56:14)
    at Layer.handle [as handle_request] (/Users/rasvaan/git/digibird_api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/rasvaan/git/digibird_api/node_modules/express/lib/router/index.js:312:13)
    at /Users/rasvaan/git/digibird_api/node_modules/express/lib/router/index.js:280:7
```

**Comment by rasvaan** [comment]
Sometimes occurs on the monitor page after pressing: cmd + shirt + r  (hard refresh)
