### ISSUE TITLE
Undefined value request interpretation

### ISSUE THREAD

**Issue by rasvaan** [rasvaan/digibird_api#66]
Fix the bug in request interpretation:
error:  TypeError: Cannot read property 'then' of undefined
    at Object.module.exports.objectParameters (/scratch/digibird/digibird/api/src/helpers/request_interpretation.js:14:43)
    at /scratch/digibird/digibird/api/src/routes/index.js:14:15
    at Layer.handle [as handle_request] (/scratch/digibird/digibird/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/scratch/digibird/digibird/api/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/scratch/digibird/digibird/api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/scratch/digibird/digibird/api/node_modules/express/lib/router/layer.js:95:5)
    at /scratch/digibird/digibird/api/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/scratch/digibird/digibird/api/node_modules/express/lib/router/index.js:330:12)
    at next (/scratch/digibird/digibird/api/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/scratch/digibird/digibird/api/node_modules/express/lib/middleware/init.js:33:5)

**Comment by rasvaan** [comment]
Error is now thrown before then.
